SoftwareTracker/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"

  resources :users do
    get :manage_tools, as: :manage_tools
    resources :user_tools, only: [:create, :destroy]
  end
  
  resources :tools
  resources :categories
end

SoftwareTracker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

SoftwareTracker/app/models/category.rb
class Category < ApplicationRecord
    has_many :tools, dependent: :destroy

    scope :not_assigned_to_tool, -> (tool_id) { where.not(id: Tool.where(id: tool_id).pluck(:category_id)) }
    scope :like_text, -> (search_text) { where("name LIKE ?", "%" + search_text + "%") }
    scope :sort_by_name, -> { order(:name) }
end

SoftwareTracker/app/models/tool.rb
class Tool < ApplicationRecord
    has_many :user_tools, dependent: :destroy

    belongs_to :category

    validates :name, presence: true

    scope :order_by_name, -> { order(:name) }
    scope :order_by_category_name, -> { order("categories.name") }
    scope :like_text, -> (search_text) { where("tools.name LIKE ?", "%" + search_text + "%") }
end

SoftwareTracker/app/models/user.rb
class User < ApplicationRecord
    has_many :user_tools, dependent: :destroy

    validates :firstname, presence: true
    validates :lastname, presence: true

    scope :order_by_firstname, -> { order(:firstname) }
    scope :order_by_lastname, -> { order(:lastname) }
    scope :like_text, -> (search_text) { where("users.firstname LIKE ?", "%" + search_text + "%").or(User.where("users.lastname LIKE ?", "%" + search_text + "%")) }
end

SoftwareTracker/app/models/user_tool.rb
class UserTool < ApplicationRecord
  belongs_to :user, optional: false
  belongs_to :tool, optional: false

  scope :with_user, ->(user_id) { where(user_id: user_id) }
  scope :group_tools, -> { includes(:tool).group(:tool_id) }
  scope :top_10, -> { order("count(user_tools.tool_id) DESC").limit(10) }
  scope :order_by_tool_categories, -> { order("categories.name ASC") }
  scope :order_by_tools, -> { order("tools.name ASC") }
end

SoftwareTracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

SoftwareTracker/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    if params[:search_text].nil?
      @categories = Category.sort_by_name.all
    else
      @categories = Category.like_text(params[:search_text]).sort_by_name
    end
  end
  
  def new
    @category = Category.new
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def create
    category = Category.new(category_params)

    if category.save
      redirect_to category
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])

    if category.update(category_params)
      redirect_to category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

SoftwareTracker/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user_tools = UserTool.group_tools.top_10
  end
end

SoftwareTracker/app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    if params[:search_text].nil?
      @tools = Tool.includes(:category).order_by_category_name.order_by_name
    else
      @tools = Tool.includes(:category).like_text(params[:search_text]).order_by_category_name.order_by_name
    end
  end
  
  def new
    @tool = Tool.new

    @categories = Category.all
  end
  
  def show
    @tool = Tool.find(params[:id])
  end
  
  def create
    tool = Tool.new(tool_params)

    if tool.save
      redirect_to tool
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @tool = Tool.find(params[:id])

    @categories = Category.all
  end

  def update
    tool = Tool.find(params[:id])
    
    if params[:tool][:category_id].empty?
      if tool.update(name: params[:tool][:name])
        tool.update_attribute(:category_id, nil)

        redirect_to tool
      else
        render :edit, status: :unprocessable_entity
      end
    else
      if tool.update(name: params[:tool][:name], category_id: params[:tool][:category_id])
        redirect_to tool
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    tool = Tool.find(params[:id])
    tool.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def tool_params
      params.require(:tool).permit(:name, :category_id)
    end
end

SoftwareTracker/app/controllers/user_tools_controller.rb
class UserToolsController < ApplicationController

  def create
    user = User.find(params[:user_id])
    user_tools = UserTool.new(user_id: params[:user_id], tool_id: params[:tool_id])

    if user_tools.save
      redirect_to request.referrer
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    user_tools = UserTool.find(params[:id])
    user_tools.destroy

    redirect_to request.referrer, status: :see_other
  end

  private
    def user_tool_params
      params.require(:user_tool).permit(:user_id, :tool_id)
    end
end

SoftwareTracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:search_text].nil?
      @users = User.order_by_firstname.order_by_lastname
    else
      @users = User.like_text(params[:search_text]).order_by_firstname.order_by_lastname
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    user = User.new(user_params)

    if user.save
      redirect_to user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])

    if user.update(user_params)
      redirect_to user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy

    redirect_to root_path, status: :see_other
  end

  def manage_tools
    @unassigned_tools = Tool.includes(:category).where.not(id: UserTool.with_user(params[:user_id]).pluck(:tool_id)).order_by_category_name.order_by_name
    @assigned_tools = UserTool.includes(:tool).with_user(params[:user_id]).order_by_tools
  end

  private
    def user_params
      params.require(:user).permit(:firstname, :lastname)
    end
end

SoftwareTracker/app/helpers/application_helper.rb
module ApplicationHelper
end

SoftwareTracker/app/helpers/categories_helper.rb
module CategoriesHelper
end

SoftwareTracker/app/helpers/tools_helper.rb
module ToolsHelper
end

SoftwareTracker/app/helpers/user_tools_helper.rb
module UserToolsHelper
end

SoftwareTracker/app/helpers/users_helper.rb
module UsersHelper
end

SoftwareTracker/app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <p>
    <%= form.submit %>
    <% if category.id.nil? %>
      <%= link_to "Cancel", categories_path %>
    <% else %>
      <%= link_to "Cancel", category_path(id: category.id) %>
    <% end %>
  </p>
<% end %>

SoftwareTracker/app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render "form", category: @category %>

SoftwareTracker/app/views/categories/index.html.erb
<h1>Categories</h1>

<%= form_with url: categories_path, method: :get do |form| %>
  <%= form.text_field :search_text, value: params[:search_text], placeholder: 'Enter search term...' %>
  <%= form.submit "Search" %>
<% end %>

<ul>
<% unless @categories.nil? %>
  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, category %>
    </li>
  <% end %>
<% end %>
</ul>

<%= link_to "New Category", new_category_path %>

SoftwareTracker/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "form", category: @category %>

SoftwareTracker/app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<%= link_to "Edit Category Details", edit_category_path %>

SoftwareTracker/app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<h2>Top 10 used software tools</h2>
<ul>
  <% @user_tools.each do |user_tool| %>
    <li>
      <%= user_tool.tool.name %>
    </li>
  <% end %>
</ul>

SoftwareTracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Software Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <%= render 'shared/components/header_logo' %>
      <%= render 'shared/components/nav' %>
    </div>
    
    <%= yield %>
  </body>
</html>

SoftwareTracker/app/views/shared/components/_header_logo.html.erb
<%= link_to root_path do %>
<div class="header-logo">
  Software Tracker
</div>
<% end %>

SoftwareTracker/app/views/shared/components/_nav.html.erb
<nav class="nav">
  <%= link_to "Users", users_path, class: "" %>
  <%= link_to "Tools", tools_path, class: "" %>
  <%= link_to "Categories", categories_path, class: "" %>
</nav>

SoftwareTracker/app/views/tools/_form.html.erb
<%= form_with model: tool do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% tool.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <%= form.collection_select :category_id, @categories, :id, :name, :include_blank => true %>
  </div>
  <p>
    <%= form.submit %>
    <% if tool.id.nil? %>
      <%= link_to "Cancel", tools_path %>
    <% else %>
      <%= link_to "Cancel", tool_path(id: tool.id) %>
    <% end %>
  </p>
<% end %>

SoftwareTracker/app/views/tools/edit.html.erb
<h1>Edit Tool</h1>

<%= render "form", tool: @tool %>

SoftwareTracker/app/views/tools/index.html.erb
<h1>Tools</h1>
<%= link_to "New Tool", new_tool_path %>

<%= form_with url: tools_path, method: :get do |form| %>
  <%= form.text_field :search_text, value: params[:search_text], placeholder: 'Enter search term...' %>
  <%= form.submit "Search" %>
<% end %>

<% unless @tools.nil? %>
  <% @tools.group_by { |tool| tool.category_id }.values.each do |tool_category| %>
    <h3>
      <% if tool_category[0].category.nil? %>
        Uncategorized
      <% else %>
        <%= tool_category[0].category.name %>
      <% end %>
    </h3>
    <ul>
      <% tool_category.each do |tool| %>
      <li>
        <%= link_to tool.name, tool %>
      </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

SoftwareTracker/app/views/tools/new.html.erb
<h1>New Tool</h1>

<%= render "form", tool: @tool %>

SoftwareTracker/app/views/tools/show.html.erb
<h1><%= @tool.name %></h1>
<h2>Category</h2>
<% unless @tool.category.nil? %>
  <p><%= @tool.category.name %></p>
<% end %>

<%= link_to "Edit Tool Details", edit_tool_path %>

SoftwareTracker/app/views/user_tools/_user_tool.html.erb
<li>
  <%= user_tool.tool.name %>
</li>

SoftwareTracker/app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label "First name" %><br>
    <%= form.text_field :firstname %>
    <% user.errors.full_messages_for(:firstname).each do |messages| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label "Last name" %><br>
    <%= form.text_field :lastname %>
    <% user.errors.full_messages_for(:lastname).each do |messages| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <p>
    <%= form.submit %>
    <% if user.id.nil? %>
      <%= link_to "Cancel", users_path %>
    <% else %>
      <%= link_to "Cancel", user_path(id: user.id) %>
    <% end %>
  </p>
<% end %>

SoftwareTracker/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

SoftwareTracker/app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to "New User", new_user_path %>

<%= form_with url: users_path, method: :get do |form| %>
  <%= form.text_field :search_text, value: params[:search_text], placeholder: 'Enter search term...' %>
  <%= form.submit "Search" %>
<% end %>

<ul>
<% unless @users.nil? %>
  <% @users.each do |user| %>
    <li>
      <%= link_to "#{user.firstname} #{user.lastname}", user %>
    </li>
  <% end %>
<% end %>
</ul>

SoftwareTracker/app/views/users/manage_tools.html.erb
<h1>Tools To Add</h1>
<div class="tool-list">
    <% @unassigned_tools.each do |tool| %>
      <div class="tool-list_container">
        <div class="tool-list_container_label"><%= tool.name %></div>
        <%= button_to user_user_tools_path(tool_id: tool.id), class: "btn add-icon" do %>
          <i class="fa fa-plus" aria-hidden="true"></i>
        <% end %>
      </div>
    <% end %>
</div>

<h1>Tools To Delete</h1>
<div class="tool-list">
    <% @assigned_tools.each do |user_tool| %>
      <div class="tool-list_container">
        <div class="tool-list_container_label"><%= user_tool.tool.name %></div>
        <%= button_to user_user_tool_path(id: user_tool.id), :method => :delete, class: "btn minus-icon" do %>
          <i class="fa fa-minus" aria-hidden="true"></i>
        <% end %>
      </div>
    <% end %>
</div>
<%= link_to "Back", user_path(id: params[:user_id]) %>

SoftwareTracker/app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

SoftwareTracker/app/views/users/show.html.erb
<h1><%= "#{@user.firstname} #{@user.lastname}" %></h1>

<ul>
  <%= render @user.user_tools %>
</ul>

<%= link_to "Manage Tool List", user_manage_tools_path(user_id: @user.id) %>
<%= link_to "Edit User Details", edit_user_path %>